project_name: aictl

env:
- GO111MODULE=on

before:
  hooks:
  - go mod tidy

gomod:
  proxy: false

sboms:
- artifacts: binary

builds:
- binary: aictl
  mod_timestamp: '{{ .CommitTimestamp }}'
  dir: .
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}}
  - -s -w -X main.commit={{.ShortCommit}}
  - -s -w -X main.date={{.Date}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: mchmarny
    name: aictl
  prerelease: auto

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - readme
    - typo
    - "version bump"

# brews:
# - tap:
#     owner: mchmarny
#     name: homebrew-aictl
#     token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#   homepage: "https://github.com/mchmarny/aictl"
#   description: "Vulnerability Import CLI"
#   folder: Formula
#   license: "Apache-2.0"
#   test: |
#     system "#{bin}/aictl --version"

# nfpms:
# - file_name_template: "aictl-{{.Version}}_{{.Os}}-{{.Arch}}"
#   homepage: https://github.com/mchmarny/aictl/
#   description: "Vulnerability Import CLI"
#   maintainer: aictl developers <aictl@thingz.io>
#   license: Apache 2.0
#   vendor: aictl developers
#   formats:
#   - deb
#   - rpm
#   bindir: /usr/bin

universal_binaries:
- replace: true
  name_template: 'aictl'
